{% set name = "dragon-ml-toolbox" %}
{% set version = "1.4.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dragon_ml_toolbox-{{ version }}.tar.gz
  sha256: d8eddf93d7a648cae92077df0f654d0416a407a0041782ce67f3ece4e19b1c9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - scikit-learn
    - openpyxl
    - miceforest
    - matplotlib-base
    - seaborn
    - pandas
    - polars
    - imbalanced-learn
    - statsmodels
    - ipython
    - joblib
    - xgboost
    - lightgbm
    - shap

test:
  imports:
    - ml_tools
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/DrAg0n-BoRn/ML_tools
  summary: A collection of tools for data science and machine learning projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DrAg0n-BoRn
