{% set name = "dragon-ml-toolbox" %}
{% set version = "2.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dragon_ml_toolbox-{{ version }}.tar.gz
  sha256: cc24cb081dc0f53d9b430f5e5422cda2dfb52a64b72a68e0a2d86ec6d28e3f3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - scikit-learn
    - openpyxl
    - miceforest
    - matplotlib-base
    - seaborn
    - pandas
    - polars
    - imbalanced-learn
    - statsmodels
    - ipython
    - joblib
    - xgboost
    - lightgbm
    - shap

test:
  imports:
    - ml_tools
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/DrAg0n-BoRn/ML_tools
  summary: A collection of tools for data science and machine learning projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DrAg0n-BoRn
