{% set name = "dragon-ml-toolbox" %}
{% set version = "10.12.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dragon_ml_toolbox-{{ version }}.tar.gz
  sha256: c3501422df3dc961ea304aeaa6e949281ff9828af21fabd3bc18eb844e889ad5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ml_tools
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/DrAg0n-BoRn/ML_tools
  summary: A collection of tools for data science and machine learning projects
  license: MIT
  license_file:
    - LICENSE
    - LICENSE-THIRD-PARTY.md

extra:
  recipe-maintainers:
    - DrAg0n-BoRn
