{% set name = "dragon-ml-toolbox" %}
{% set version = "26.3.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/dragon_ml_toolbox-{{ version }}.tar.gz
  sha256: 01046d40193527db259387cd2c70f3d7a9791d959e283ad366eb753126c3970c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - dragon
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/DrAg0n-BoRn/ML_tools
  summary: Complete pipelines and helper tools for data science and machine learning projects.
  license: MIT
  license_file:
    - LICENSE
    - LICENSE-THIRD-PARTY.md

extra:
  recipe-maintainers:
    - DrAg0n-BoRn
